main: me.thebirmanator.autoworldreset.AutoWorldReset
name: AutoWorldReset
version: 1.1
author: TheBirmanator
api-version: 1.14
description: Simple auto reset plugin for specific Minecraft worlds
depend: [Multiverse-Core, WorldBorder]